# Configuration File for SIMULATION 1

simulation_n : 0
simulation_name : "Simulation 0: JASM: Just Another Sirs Model"



# Model parameters

model_type: 'sirs_delay_incidence'

r0 : 15
theta : !expr 1/30
mu : !expr 0
gamma : !expr 1/14
a1 : !expr 1/15
a2 : !expr 1/90
k1 : 1.
k2 : 1.
alpha1 : 100.
alpha2 : 100.

delta : 0.
omega : 0.
T : 365


# Simulation parameters

t_span : [0, 2500]
n_points : 250000
initial_conditions : [0.001, 0., 0.]

method : 'Tsit5'






# Plotting parameters

show_cumulative_incidence : False
show_params : False
show_title : False

plot_together : True
plot_t_span : [0, 2500]
plot_n_points : 250000

plot_path : "./code/img/simulation_00/"