# Configuration File for SIMULATION 17

simulation_n : 17
simulation_name : "Simulation 17: RH5 - plot a1, a2, a3"



# Model parameters

model_type: 'sirs_three_layer_incidence_one_memory'

r0 : 2.
theta : !expr 1/365
mu : !expr 1/365/80
gamma : !expr 1/14
a1 : !expr 1/15
a2 : !expr 1/90
a3 : !expr 1/10/365
k1 : 1.
k2 : 1.
alpha1 : 1.
alpha2 : 1.
alpha3 : 1.

delta : 0.
omega : 0.

t_span : [0, 10000]
initial_conditions : [0.001, 0., 0., 0., 0. ]

target_span : [0, 0.1]
target_n_points : 30


# Plotting parameters
'plot_type' : '3D'
'save_plot' : True
#'plot_type' : 'Combo'
#'plot_type' : 'Voxel'