# Configuration File for SIMULATION 14

simulation_n : 0
simulation_name : "Simulation 14: RH3"



# Model parameters

model_type: 'sirs_one_layer'

r0 : 2.
theta : !expr 1/365
mu : !expr 1/365/80
gamma : !expr 1/14
a1 : !expr 1/15
a2 : !expr 1/90
k1 : 1.
k2 : 1.
alpha1 : 50.
alpha2 : 50.

delta : 0.
omega : 0.

t_span : [0, 10000]
initial_conditions : [0.001, 0., 0.]


target : 'a1'
target_span : [0, 1]
target_n_points : 100

# Plotting parameters

show_cumulative_incidence : False
show_params : False
show_title : False

plot_together : False
plot_t_span : [0, 1250]